/**
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.dev/license
 */
import {InjectFlags} from '../../di/flags';
import {InjectInjector, inject} from '../../di/inject';
import {ProviderToken} from '../../di/provider_token';
import {resolveForwardRef} from '../../forward_ref';
import {Type} from '../../interface/type';
import {assertDefined} from '../../util/assert';
import {emitInjectEvent} from '../debug/injector_profiler';
import {getOrCreateInjectable} from '../di';
import {TDirectiveHostNode} from '../interfaces/node';
import {getCurrentTNode, getLView} from '../state';

/**
 * Returns the value associated to the given token by looking in the node tree.
 *
 * `DIRECTIVE_INJECTOR` is installed when the runtime constructs directives, components, and pipes.
 *  All other injection does not walk the node injector tree.
 */
export const DIRECTIVE_INJECTOR: InjectInjector = {
  get(token: unknown, _: undefined, flags: InjectFlags): unknown {
    const lView = getLView();
    ngDevMode && assertDefined(lView, `DIRECTIVE_INJECTOR installed but no LView`);
    const tNode = getCurrentTNode();
    return getOrCreateInjectable(
      tNode as TDirectiveHostNode,
      lView,
      resolveForwardRef(token as ProviderToken<unknown>),
      flags,
    );
  },
};

/**
 * Throws an error indicating that a factory function could not be generated by the compiler for a
 * particular class.
 *
 * This instruction allows the actual error message to be optimized away when ngDevMode is turned
 * off, saving bytes of generated code while still providing a good experience in dev mode.
 *
 * The name of the class is not mentioned here, but will be in the generated factory function name
 * and thus in the stack trace.
 *
 * @codeGenApi
 */
export function ɵɵinvalidFactory(): never {
  const msg = ngDevMode
    ? `This constructor was not compatible with Dependency Injection.`
    : 'invalid';
  throw new Error(msg);
}
